language: go
# command to install dependencies
install:
  - sudo pip install -r requirements.txt
  - go install github.com/onsi/ginkgo/ginkgo
# command to run tests
script: 
  - ginkgo -r --keepGoing src/github.com/bitpay/ 
